### ISSUE TITLE
Incompatability with the mod Linear XP Levels.

### ISSUE THREAD

**Issue by Romoslayer** [bl4ckscor3/XP-Tome#17]
Link to the incompatible mod: https://www.curseforge.com/minecraft/mc-mods/linear-xp-levels

What happens:
Basically whenever you store XP and right-click to get it back from the tome all the experience gets deleted.

video showing what happens:
https://www.youtube.com/watch?v=C3s-dN_xUFg&ab_channel=Romoslayer2.0

Ways to add compatibility:
Could add to the config and allow users to choose between storing experience points or levels.

XP Tome mod version: 1.16.5-2.1.4
Forge version: 1.16.5-36.2.20

**Comment by bl4ckscor3** [comment]
That mod does not properly update all the player's XP values. This is not on me to fix.
