### ISSUE TITLE
[Suggestion] Config or way to retrieve single level from tome

### ISSUE THREAD

**Issue by Charles445** [bl4ckscor3/XP-Tome#6]
Right clicking currently retrieves all XP from a tome. 
It'd be very useful to be able to configure the tome to retrieve only the XP needed to reach the next enchantment level (like EnderIO's Experience Rod).
This would make it a lot easier to get precise levels without wasting XP.

**Comment by bl4ckscor3** [comment]
Closed by 4a2053bbf62ea66c71a5b6d0729dc4abfb469307
