### ISSUE TITLE
Loses XP

### ISSUE THREAD

**Issue by TamanduaGirl** [bl4ckscor3/XP-Tome#7]
This is being used in RL craft but should be easy to recreate just keep track of your xp as you put it in and you'll see you have less levels when you take it out. Requires adding xp at least twice. Like tonight I know I had 14 levels + some xp in the tome and then added 2 levels plus some xp, then took it out and had only 14 levels and some xp, it should have been at least 16 but closer to 17 levels. later just to have 2 examples I put in 9 + some and then added 2+ some, took it out and only had 10 levels. I've lost even larger amounts before.

Since this is a long time bug I'm guess it hasn't been reported before, maybe people aren't keeping track of what they put in so don't notice they lose, but it's annoying when you do notice it, especially if you planned on using the levels only to find you don't actually have what you need since some was lost.

Everything I looked up said there is supposed to be no cost for using the tome and none is lost if I only put levels in once but if I add to it some is usually lost.

**Comment by bl4ckscor3** [comment]
Minecraft's leveling system scales with the amount of levels you have. If you have 2 levels on your XP bar, it's less XP than leveling up from level 14 to level 16. The tome stores the raw XP, not the levels. I'm assuming that when you added those 2 levels, they were all the levels you had, meaning you would have added a fairly small amount of XP to the book. Is that the case?

**Comment by TamanduaGirl** [comment]
Oh, okay. That makes sense. It's been with varying amounts. If I kept track of how many levels put in I'd get less back than I expected. But yeah I'm new to minecraft so didn't realize that it was minecraft it's self doing it. 

Thank you for explaining.
